# PostgreSQL. Versions 8.2 and up are supported.
#
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: mobilebook_loc



test:
  <<: *default
  database: mobilebook_demo

production:
  <<: *default
  database: mobilebook_prod
  username: opu
  password: <%= ENV['MOBILEBOOK_DATABASE_PASSWORD'] %>
